//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        public int GoodsID { get; set; }
        public string GoodsName { get; set; }
        public Nullable<decimal> RentPrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<int> GoodsSortID { get; set; }
        public Nullable<int> ProductsSortID { get; set; }
        public Nullable<int> StockQuntity { get; set; }
        public Nullable<int> Quntity { get; set; }
        public Nullable<int> Multiple { get; set; }
        public string StockUnite { get; set; }
        public string MeasureUnite { get; set; }
        public string GoodsPic { get; set; }
        public string GoodsBrife { get; set; }
        public string Features { get; set; }
        public string Specifications { get; set; }
        public string Supplies { get; set; }
    
        public virtual GoodsSort GoodsSort { get; set; }
        public virtual ProductsSort ProductsSort { get; set; }
    }
}
