//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsSort
    {
        public GoodsSort()
        {
            this.Goods = new HashSet<Good>();
        }
    
        public int GoodsSortId { get; set; }
        public string GoodsSortName { get; set; }
        public Nullable<int> ProductsSortID { get; set; }
    
        public virtual ICollection<Good> Goods { get; set; }
        public virtual ProductsSort ProductsSort { get; set; }
    }
}
