//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.RolePermissions = new HashSet<RolePermission>();
            this.VipUserPermissions = new HashSet<VipUserPermission>();
        }
    
        public int PermissionID { get; set; }
        public string Description { get; set; }
        public string Parent { get; set; }
        public string Name { get; set; }
        public string AreaName { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public Nullable<int> FormMethod { get; set; }
        public string OperationType { get; set; }
        public string Ico { get; set; }
        public Nullable<int> PerMissionOrder { get; set; }
        public Nullable<bool> IsLink { get; set; }
        public string LinkUrl { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    
        public virtual ICollection<RolePermission> RolePermissions { get; set; }
        public virtual ICollection<VipUserPermission> VipUserPermissions { get; set; }
    }
}
