//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsSort
    {
        public ProductsSort()
        {
            this.Goods = new HashSet<Good>();
            this.GoodsSorts = new HashSet<GoodsSort>();
        }
    
        public int ProductsSortID { get; set; }
        public string ProductsSortName { get; set; }
        public string ProductsSortLogo { get; set; }
        public string ProductsSortBrife { get; set; }
        public string ProductsSortWeb { get; set; }
    
        public virtual ICollection<Good> Goods { get; set; }
        public virtual ICollection<GoodsSort> GoodsSorts { get; set; }
    }
}
