//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int RoleID { get; set; }
        public string Description { get; set; }
        public Nullable<int> DeptmentID { get; set; }
        public string RoleName { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
