//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDB
    {
        public UserDB()
        {
            this.UserRoles = new HashSet<UserRole>();
            this.VipUserPermissions = new HashSet<VipUserPermission>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string NickName { get; set; }
        public string Degree { get; set; }
        public string College { get; set; }
        public string QQ { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Telphone { get; set; }
        public string Pic { get; set; }
        public string Img { get; set; }
        public Nullable<int> Rights { get; set; }
        public string Brief { get; set; }
        public string Author { get; set; }
        public string Film { get; set; }
        public string Sex { get; set; }
        public Nullable<int> PosterNumber { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public string IsForumClass { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public Nullable<int> DepartID { get; set; }
    
        public virtual DepartMent DepartMent { get; set; }
        public virtual UserDB UserDB1 { get; set; }
        public virtual UserDB UserDB2 { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual ICollection<VipUserPermission> VipUserPermissions { get; set; }
    }
}
